config/routes.rb
ReleasePackager::Application.routes.draw do
  authenticated :user do
    root :to => 'releases#index'
  end
  root :to => "releases#index"

  devise_for :users
  resources :users, :only => [:show, :index]

  resources :releases do
	member do
	  get 'generate'
	end  	
  end

  resources :system_configs
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/release.rb
class Release < ActiveRecord::Base
  attr_accessible :commit_id, :release_tag, :release_message

  before_save :set_attrs, :pack_release

  default_scope :order => "created_at DESC"

  def self.valid_commits
  	@repo = Grit::Repo.new(SystemConfig.first.repo_dir)
  	if Release.count == 0
      @repo.commits
  	else
  	  last_committed_date = @repo.commit(Release.last.commit_id).committed_date
  	  @repo.commits.reject!{|commit| commit.committed_date <= last_committed_date}
  	end
  end

  def set_attrs
  	self.release_tag.gsub!(' ', '_')
  	self.package_file_name = "#{self.release_tag}_#{Time.now.strftime('%d_%m_%Y-%I_%M_%p')}.zip"
  	self.package_file_path = File.join(SystemConfig.first.package_dir, self.package_file_name)
  end

  def pack_release
  	`cd #{SystemConfig.first.repo_dir} && git checkout #{SystemConfig.first.repo_branch} && git checkout #{self.commit_id} && git tag #{self.release_tag} #{self.commit_id}`
  	`zip -r -q #{self.package_file_path} #{SystemConfig.first.repo_dir}`
  end


end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/system_config.rb
class SystemConfig < ActiveRecord::Base
  attr_accessible :repo_name, :repo_dir, :package_dir, :repo_branch
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end



end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController


  def index
  	if SystemConfig.first.blank?
  	  redirect_to :controller => 'system_configs', :action => 'new'
  	else
	  @commits = Release.valid_commits
	  @releases = Release.all
	  @release = Release.new
  	end	
  end

  def new
  	@release = Release.new
  	@commits = Release.valid_commits
  end

  def create
  	@release = Release.new(params[:release])

  	if @release.save
	  redirect_to :action => 'index'
  	else
      render :action => 'new'
  	end
  end

  def generate
  	release = Release.find(params[:id])
  	release.save
	redirect_to :action => 'index'
  end
 

end

app/controllers/system_configs_controller.rb
class SystemConfigsController < ApplicationController
  def new
  	if SystemConfig.first.blank?
  	  @system_config = SystemConfig.new  	
  	else
  	  redirect_to :controller => 'releases', :action => 'index'		
  	end  
  end

  def create
  	@system_config = SystemConfig.new(params[:system_config])
  	@system_config.save
  	if @system_config.save
	  redirect_to :controller => 'releases', :action => 'index'
  	else
      render :action => 'new'
  	end  	
  end

  def index  	
  	@system_config = SystemConfig.first
  	render :action => 'edit'
  end

  def edit
  	@system_config = SystemConfig.first
  end

  def update
  	@system_config = SystemConfig.first
  	if @system_config.update_attributes(params[:system_config])  	
  	  redirect_to :controller => 'releases', :action => 'index'
  	else
  	  render :action => 'edit'		
  	end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def formatted_datetime(date_time)
  	date_time.strftime('%d/%m/%Y %I:%m %p')
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
	def commits_collections(commits)
		commits.map{|commit| ["#{formatted_datetime(commit.committed_date)} - #{commit.committer} - #{commit.message}", commit.id]}
	end
end

app/helpers/system_configs_helper.rb
module SystemConfigsHelper
end

app/views/home/index.html.haml
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Release Packager", root_path, :class => 'brand'

.nav-collapse
  %ul.nav.pull-left
    %li{:class => controller.controller_name == 'releases' ? 'active' : ''}
      = link_to('Releases', releases_path)
    %li{:class => controller.controller_name == 'system_configs' ? 'active' : ''}
      = link_to('Configs', system_configs_path)

%ul.nav.pull-right
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Release Packager"
      %meta{:content => content_for?(:description) ? yield(:description) : "Release Packager", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer
      / ! end of .container
    / ! end of #main

app/views/releases/_form.html.haml
%h2
  Release
= simple_form_for(@release, :html => {:class => "form-horizontal"}) do |f|
  = f.error_notification
 
  %fieldset 
    .row
      .span12
        .inputs
          = f.input :commit_id, :collection => commits_collections(@commits), :input_html => { :class => 'span6'}
      .span12
        .inputs                
          = f.input :release_tag, :input_html => { :class => 'span6'}
      .span12
        .inputs                
          = f.input :release_message, :input_html => { :class => 'span6'}

  %fieldset      
    .actions
      = f.button :submit, "#{@release.new_record? ? 'Create' : 'Update'}", :class=> 'btn btn-primary', :disabled_with => 'Please Wait'
      = link_to "Back", releases_path(), :class=> 'btn btn-primary'

app/views/releases/index.html.haml
%legend
  New Release

= simple_form_for(@release, :html => {:class => "form-horizontal"}) do |f|
  = f.error_notification
 
  %fieldset 
    .row
      .span12
        .inputs
          = f.input :commit_id, :collection => commits_collections(@commits), :input_html => { :class => 'span6'}
      .span12
        .inputs                
          = f.input :release_tag, :input_html => { :class => 'span6'}
      .span12
        .inputs                
          = f.input :release_message, :input_html => { :class => 'span6'}

  %fieldset  
    .actions
      = f.button :submit, "Create Release", :class=> 'btn btn-primary', :disabled_with => 'Please Wait'


%legend
  Existing Releases

.row
  .span12
    %table.table.table-striped
      %thead
        %tr
          %th ID
          %th Commit ID
          %th Tag
          %th Message
          %th Package File
          %th Created At
          %th &nbsp


      %tbody
        - if @releases.blank? 
          %tr
            %td{:colspan => 6}
              No releases records

        - else
          - @releases.each do |release|
            %tr
              %td
                = release.id
              %td
                = release.commit_id
              %td
                = release.release_tag
              %td
                = release.release_message
              %td
                %div{:title => release.package_file_path}
                  = release.package_file_name
              %td
                = release.created_at.strftime('%d/%m/%Y %I:%m %p')
              %td
                = link_to "ReGenerate", generate_release_path(release) , :class => "btn btn-primary"

app/views/system_configs/_form.html.haml
%h2
  Config

= simple_form_for(@system_config, :html => {:class => "form-horizontal"}) do |f|
  = f.error_notification
 
  %fieldset 
    .row
      .span12
        .inputs                
          = f.input :repo_name, :input_html => { :class => 'span6'}
      .span12
        .inputs                
          = f.input :repo_dir, :input_html => { :class => 'span6'}
      .span12
        .inputs                
          = f.input :repo_branch, :input_html => { :class => 'span6'}
      .span12
        .inputs                
          = f.input :package_dir, :input_html => { :class => 'span6'}

  %fieldset      
    .actions
      = f.button :submit, "Save", :class=> 'btn btn-primary', :disabled_with => 'Please Wait'

app/views/system_configs/edit.html.haml
= render 'form'

app/views/system_configs/new.html.haml
= render 'form'

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}